name: fluttertemplate
description: Flutter Template
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.3.7
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^10.1.0
  google_mobile_ads: ^3.0.0
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  riverpod_annotation: ^2.1.2
  youtube_player_flutter: ^8.1.2
  get_it: ^7.6.4
  firebase_analytics: ^10.6.3
  firebase_core: ^2.21.0
  pretty_dio_logger: ^1.3.1
  tab_indicator_styler: ^2.0.0
  async_preferences: ^0.8.0
  flutter_rating_bar: ^4.0.1
  launch_app_store: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  custom_lint: ^0.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/icon/icon.png"
  image_dark: "assets/icon/icon.png"
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: "assets/icon/small_icon.png"
    image_dark: "assets/icon/small_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
    - assets/icon/
